// <auto-generated />
namespace Price.Db.MysSql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V01));
        
        string IMigrationMetadata.Id
        {
            get { return "201802160804077_V01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
